version: "3.8"
services:
  app:
    container_name: "springbootcontainer"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/MongoDocker
    depends_on:
      - mongo

  mongo:
    container_name: "mongo_db"
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:


